In [2]:
import json
from functools import partial
from typing import List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from catboost import CatBoostClassifier, Pool
from catboost.utils import eval_metric
from scipy.spatial.distance import cosine, euclidean
from sklearn.metrics import pairwise_distances
from sklearn.model_selection import train_test_split

from sklearn.metrics import precision_score


### Load data

In [77]:
dataset = pd.read_parquet(r"C:\Users\druzh\Project_python\ozon_top_1\Datasets/train_pairs.parquet")
etl = pd.read_parquet(r"C:\Users\druzh\Project_python\ozon_top_1\Datasets/train_data.parquet")

In [78]:
data_test = pd.read_parquet(r"C:\Users\druzh\Project_python\ozon_top_1\Datasets/test_pairs_wo_target.parquet")
etl_test = pd.read_parquet(r"C:\Users\druzh\Project_python\ozon_top_1\Datasets/test_data.parquet")

In [79]:
dataset.head(2)

target  variantid1  variantid2
0     0.0    51197862    51198054
1     1.0    53062686   536165289

In [80]:
dataset["target"].value_counts()

0.0    171527
1.0    135013
Name: target, dtype: int64

In [81]:
etl_test.head(8)

variantid                                               name  \
0   51201254  Колодка TDM Electric четырехместная без заземл...   
1   77151532    Клавиатура черная с черной рамкой для 25-011879   
2   89664856  15.6" Игровой ноутбук Acer Predator Helios 300...   
3   90701982  Портативная колонка Borofone BR7 Empyreal Spor...   
4   92484118                Аккумулятор для Meizu BA712 ( M6s )   
5   99097578   Клавиатура черная с черной рамкой для Asus N43JM   
6  120558024  KX-FAT411A (Colouring) тонер картридж - 2000 с...   
7  133489315  Виниловый фотофон для предметной съемки стена-...   

                                          categories    color_parsed  \
0  {"1": "EPG", "2": "Электроника", "3": "Сетевые...         [белый]   
1  {"1": "EPG", "2": "Электроника", "3": "Запчаст...        [черный]   
2  {"1": "EPG", "2": "Электроника", "3": "Компьют...        [черный]   
3  {"1": "EPG", "2": "Электроника", "3": "Акустик...  [red, красный]   
4  {"1": "EPG", "2": "Электроника", "3": "Батарей...            None   
5  {"1": "EPG", "2": "Электроника", "3": "Запчаст...        [черный]   
6  {"1": "EPG", "2": "Электроника", "3": "Расходн...        [черный]   
7  {"1": "EPG", "2": "Электроника", "3": "Аксессу...    [коричневый]   

                            pic_embeddings_resnet_v1  \
0  [[0.34383398, -0.2962618, 0.07987049, -0.08257...   
1                                               None   
2  [[0.7804302, -0.245446, -0.67754817, -0.614691...   
3  [[-0.24636984, -1.0719914, -0.49986655, 0.3423...   
4                                               None   
5                                               None   
6                                               None   
7                                               None   

                       main_pic_embeddings_resnet_v1  \
0  [[0.38310742, -0.7876679, 0.5018278, 0.2090071...   
1  [[0.50964713, 0.7958329, -1.4113188, 0.1999381...   
2  [[0.9958085, -0.113175124, -0.7623152, -0.9164...   
3  [[-0.26596686, -1.143009, -0.5289628, 0.428558...   
4  [[0.42047608, 0.75828516, 0.5440093, -0.006894...   
5  [[0.987125, 0.87486434, -0.8414553, -0.1438423...   
6  [[-0.9767299, 1.2299631, 0.88899034, 0.4193062...   
7  [[-0.3676244, -0.2502277, -0.42328912, 0.19049...   

                                        name_bert_64  \
0  [-0.5060825, 0.5773388, 0.59435517, -0.4958292...   
1  [-0.43467724, 0.6614495, 0.48050267, -0.588880...   
2  [-0.70010763, 0.48152006, 0.47597092, -0.51727...   
3  [-0.73135185, -0.039796613, 0.38907066, -0.496...   
4  [-0.600158, 0.13944691, 0.48706242, -0.5050975...   
5  [-0.71254474, 0.6018984, 0.48035166, -0.578878...   
6  [-0.3799147, 0.56713665, 0.63711894, -0.437501...   
7  [-0.46177715, 0.5542605, 0.40788603, -0.349237...   

                   characteristic_attributes_mapping  
0  {"Страна-изготовитель":["Китай"],"Бренд":["TDM...  
1  {"Страна-изготовитель":["Китай"],"Комплектация...  
2  {"Видеокарта":["NVIDIA GeForce RTX 2070 (8 Гб)...  
3  {"Основной материал корпуса":["Металл"],"Макси...  
4  {"Рекомендовано для":["Meizu"],"Бренд":["Meizu...  
5  {"Рекомендовано для":["ASUS"],"Страна-изготови...  
6  {"Цвет тонера/чернил":["черный"],"Страна-изгот...  
7  {"Ширина, см":["50"],"Страна-изготовитель":["Р...

In [82]:
print(etl.shape, dataset.shape)

(457063, 8) (306540, 3)


Get raw data for each variantid.

In [83]:
features0 = (
    dataset
    .merge(
        etl
        .add_suffix('1'),
        on="variantid1"
    )
    .merge(
        etl
        .add_suffix('2'),
        on="variantid2"
    )
)

In [84]:
feature_test = (
    data_test
    .merge(
        etl_test
        .add_suffix('1'),
        on="variantid1"
    )
    .merge(
        etl_test
        .add_suffix('2'),
        on="variantid2"
    )
)

In [85]:
feature_test.head(2)

variantid1  variantid2                                              name1  \
0    52076340   290590137  Батарейка AAA щелочная Perfeo LR03/10BL Super ...   
1    64525522   204128919  Смартфон Ulefone Armor X5 3/32 ГБ, черный, кра...   

                                         categories1           color_parsed1  \
0  {"1": "EPG", "2": "Электроника", "3": "Батарей...                    None   
1  {"1": "EPG", "2": "Электроника", "3": "Смартфо...  [черный, red, красный]   

                           pic_embeddings_resnet_v11  \
0  [[0.15417035, 0.41160947, 0.2213532, -0.019731...   
1  [[-0.239386, -0.8332473, -0.08384809, 0.071721...   

                      main_pic_embeddings_resnet_v11  \
0  [[0.04763528, -0.20136409, 0.29605597, 0.26453...   
1  [[-0.27325493, -0.6696304, 0.027148303, 0.0785...   

                                       name_bert_641  \
0  [-0.28437558, 0.60909724, 0.5972025, -0.523296...   
1  [-0.45766184, 0.5528555, 0.26298037, -0.663931...   

                  characteristic_attributes_mapping1  \
0  {"Напряжение, В":["1.5"],"Бренд":["Perfeo"],"Т...   
1  {"Операционная система":["Android"],"Защищенно...   

                                               name2  \
0  Батарейка AAA щелочная Perfeo LR03/2BL mini Su...   
1  Смартфон Ulefone Armor X3 2/32 ГБ, черный, кра...   

                                         categories2           color_parsed2  \
0  {"1": "EPG", "2": "Электроника", "3": "Батарей...                    None   
1  {"1": "EPG", "2": "Электроника", "3": "Смартфо...  [черный, red, красный]   

                           pic_embeddings_resnet_v12  \
0  [[-0.025554053, 0.012488857, 0.43989864, -0.10...   
1  [[-0.071279265, -0.99063504, -0.3939417, 0.886...   

                      main_pic_embeddings_resnet_v12  \
0  [[0.06223978, -0.16145544, 0.26409012, 0.24271...   
1  [[-0.15358369, -0.8256463, -0.054863703, 0.453...   

                                       name_bert_642  \
0  [-0.3380968, 0.6156224, 0.6428071, -0.57499236...   
1  [-0.4489074, 0.6278857, 0.33072582, -0.6749875...   

                  characteristic_attributes_mapping2  
0  {"Форм-фактор батареи":["AAA"],"Химический тип...  
1  {"Встроенная память":["32 ГБ"],"Видеопроцессор...

Features functions.

In [13]:
features = features0

In [14]:
features["cat31"] = features["categories1"].apply(lambda x: json.loads(x)["3"])
cat3_counts = features["cat31"].value_counts().to_dict()

In [15]:
feature_test["cat31"] = feature_test["categories1"].apply(lambda x: json.loads(x)["3"])
cat3_counts_test = feature_test["cat31"].value_counts().to_dict()

In [16]:
features["cat31_grouped"] = features["cat31"].apply(lambda x: x if cat3_counts[x] > 1000 else "rest")
feature_test["cat31_grouped"] = feature_test["cat31"].apply(lambda x: x if cat3_counts_test[x] > 1000 else "rest")

In [17]:
features["cat32"] = features["categories2"].apply(lambda x: json.loads(x)["3"])
cat3_counts = features["cat32"].value_counts().to_dict()

feature_test["cat32"] = feature_test["categories2"].apply(lambda x: json.loads(x)["3"])
cat3_counts_test = feature_test["cat32"].value_counts().to_dict()

In [18]:
features["cat32_grouped"] = features["cat32"].apply(lambda x: x if cat3_counts[x] > 1000 else "rest")
feature_test["cat32_grouped"] = feature_test["cat32"].apply(lambda x: x if cat3_counts_test[x] > 1000 else "rest")

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

def create_top_bag_of_words(sentences, top_words):
    vectorizer = CountVectorizer(max_features=top_words)
    bag_of_words = vectorizer.fit_transform(sentences)
    len_sentences = [len(sentence.split()) for sentence in sentences]

    return bag_of_words, len_sentences, vectorizer

def encode_sentences(sentences, vectorizer):
    encoded_sentences = vectorizer.transform(sentences)
    len_sentences = [len(sentence.split()) for sentence in sentences]
    return encoded_sentences, len_sentences

In [21]:
bag_of_words, len_sentences, names_bag_vectorizer = create_top_bag_of_words(np.hstack((features['name1'].values, features['name2'].values)), 5000)

In [24]:
bag_of_words, len_sentences = encode_sentences(np.hstack((feature_test['name1'].values, feature_test['name2'].values)), names_bag_vectorizer)

In [25]:
bag_of_words = bag_of_words.toarray()

In [17]:
print(bag_of_words)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
feature_test["name1_bag"] = bag_of_words[:len(bag_of_words) // 2].tolist()

In [27]:
feature_test["name2_bag"] = bag_of_words[len(bag_of_words) // 2:].tolist()

In [28]:
feature_test["name1_len"] = len_sentences[:len(len_sentences) // 2]

In [29]:
feature_test["name2_len"] = len_sentences[len(len_sentences) // 2:]

In [30]:
bag_of_words, len_sentences, cats_bag_vectorizer = create_top_bag_of_words(np.hstack((features['cat31'].values, features['cat32'].values)), 250)

In [31]:
bag_of_words, len_sentences = encode_sentences(np.hstack((feature_test['cat31'].values, feature_test['cat32'].values)), cats_bag_vectorizer)

In [32]:
bag_of_words = bag_of_words.toarray()

In [33]:
feature_test["cat31_bag"] = bag_of_words[:len(bag_of_words) // 2].tolist()

In [40]:
feature_test = feature_test.drop(
        ["name1", "categories1", "pic_embeddings_resnet_v11", "main_pic_embeddings_resnet_v11", "name_bert_641",
         "name2",
         "categories2", "pic_embeddings_resnet_v12", "main_pic_embeddings_resnet_v12", "name_bert_642"], axis=1)
feature_test = feature_test.drop(['cat31', 'cat32'], axis=1)

KeyError: "['name1', 'categories1', 'pic_embeddings_resnet_v11', 'main_pic_embeddings_resnet_v11', 'name_bert_641', 'name2', 'categories2', 'pic_embeddings_resnet_v12', 'main_pic_embeddings_resnet_v12', 'name_bert_642'] not found in axis"

In [ ]:
feature_test["cat32_bag"] =  bag_of_words[len(bag_of_words) // 2:].tolist()

In [42]:
feature_test

variantid1  variantid2           color_parsed1  \
0        52076340   290590137                    None   
1        64525522   204128919  [черный, red, красный]   
2        77243372   479860557    [черный, золотистый]   
3        86065820   540678372                [черный]   
4        91566575   258840506         [черный, синий]   
...           ...         ...                     ...   
18079   666998614   667074522                 [black]   
18080   670036240   670048449                    None   
18081   670284509   684323809       [желтый, красный]   
18082   692172005   704805270                 [синий]   
18083   704060220   704096517                [черный]   

                      characteristic_attributes_mapping1  \
0      {"Напряжение, В":["1.5"],"Бренд":["Perfeo"],"Т...   
1      {"Операционная система":["Android"],"Защищенно...   
2      {"Тип":["Видео-кабель"],"Длина, м":["3"],"Разм...   
3      {"MTBF, кликов":["20000000"],"Особенности":["П...   
4      {"Процессор":["Snapdragon 439 (8 ядер), 2.0 ГГ...   
...                                                  ...   
18079  {"Бренд":["Corsair"],"Форм-фактор RAM":["DIMM"...   
18080  {"Макс. выходной ток, А":["3.33"],"Партномер":...   
18081  {"Бренд":["Нет бренда"],"Вес товара, г":["100"...   
18082  {"Бренд":["Sol"],"Вес товара, г":["200"],"Разм...   
18083  {"Тип":["Блок питания для ноутбука"],"Длина ка...   

                               color_parsed2  \
0                                       None   
1                     [черный, red, красный]   
2                       [черный, золотистый]   
3                                    [серый]   
4                                   [черный]   
...                                      ...   
18079                                   None   
18080                                   None   
18081                              [красный]   
18082  [зеленый, красный, green, red, синий]   
18083                               [черный]   

                      characteristic_attributes_mapping2  \
0      {"Форм-фактор батареи":["AAA"],"Химический тип...   
1      {"Встроенная память":["32 ГБ"],"Видеопроцессор...   
2      {"Коннектор 2":["HDMI"],"Единиц в одном товаре...   
3      {"Цвет товара":["серый"],"Интерфейс":["USB"],"...   
4      {"Модуль связи WiFi":["802.11a/b/g/n"],"Бренд ...   
...                                                  ...   
18079  {"Бренд":["Corsair"],"Напряжение питания, В":[...   
18080  {"Выходное напряжение, В":["19.5"],"Тип":["Бло...   
18081  {"Название цвета":["Красный"],"Страна-изготови...   
18082  {"Автофокус":["Да"],"Комплектация":["- Лазерны...   
18083  {"Комплектация":["Зарядное устройство, сетевой...   

                           cat31_grouped                      cat32_grouped  \
0                                   rest                               rest   
1                                   rest                               rest   
2                   Кабели и переходники               Кабели и переходники   
3                                   rest                               rest   
4                                   rest                               rest   
...                                  ...                                ...   
18079                               rest                               rest   
18080  Зарядные устройства и док-станции  Зарядные устройства и док-станции   
18081                         Смарт-часы                         Смарт-часы   
18082                               rest                               rest   
18083  Зарядные устройства и док-станции  Зарядные устройства и док-станции   

                                               name1_bag  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, .

In [43]:
feature_test["cat31_len"] = len_sentences[:len(len_sentences) // 2]

In [44]:
feature_test["cat32_len"] = len_sentences[len(len_sentences) // 2:]

In [45]:
feature_test.head(2)

variantid1  variantid2           color_parsed1  \
0    52076340   290590137                    None   
1    64525522   204128919  [черный, red, красный]   

                  characteristic_attributes_mapping1           color_parsed2  \
0  {"Напряжение, В":["1.5"],"Бренд":["Perfeo"],"Т...                    None   
1  {"Операционная система":["Android"],"Защищенно...  [черный, red, красный]   

                  characteristic_attributes_mapping2 cat31_grouped  \
0  {"Форм-фактор батареи":["AAA"],"Химический тип...          rest   
1  {"Встроенная память":["32 ГБ"],"Видеопроцессор...          rest   

  cat32_grouped                                          name1_bag  \
0          rest  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1          rest  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                           name2_bag  name1_len  name2_len  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          9         12   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          8          8   

                                           cat31_bag  cat31_len  cat32_len  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          3          3   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4          4   

                                           cat32_bag  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [46]:
color_1_prod = features['color_parsed1'].values
colors = []
for i in range(len(color_1_prod)):
    try:
        colors.append(color_1_prod[i][0])
    except:
        colors.append('None')
color_2_prod = features['color_parsed2'].values
for j in range(len(color_2_prod)):
    try:
        colors.append(color_2_prod[j][0])
    except:
        colors.append('None')

In [47]:
color_1_prod = feature_test['color_parsed1'].values
colors_test = []
for i in range(len(color_1_prod)):
    try:
        colors_test.append(color_1_prod[i][0])
    except:
        colors_test.append('None')
color_2_prod = feature_test['color_parsed2'].values
for j in range(len(color_2_prod)):
    try:
        colors_test.append(color_2_prod[j][0])
    except:
        colors_test.append('None')

In [48]:
bag_of_words, len_sentences, colors_bag_vectorizer = create_top_bag_of_words(colors, 200)

In [49]:
bag_of_words, len_sentences = encode_sentences(colors_test, colors_bag_vectorizer)

In [50]:
bag_of_words = bag_of_words.toarray()

In [51]:
feature_test["color1_bag"] = bag_of_words[:len(bag_of_words) // 2].tolist()

In [52]:
feature_test["color2_bag"] =  bag_of_words[len(bag_of_words) // 2:].tolist()

In [54]:
feature_test.head(2)

variantid1  variantid2           color_parsed1  \
0    52076340   290590137                    None   
1    64525522   204128919  [черный, red, красный]   

                  characteristic_attributes_mapping1           color_parsed2  \
0  {"Напряжение, В":["1.5"],"Бренд":["Perfeo"],"Т...                    None   
1  {"Операционная система":["Android"],"Защищенно...  [черный, red, красный]   

                  characteristic_attributes_mapping2 cat31_grouped  \
0  {"Форм-фактор батареи":["AAA"],"Химический тип...          rest   
1  {"Встроенная память":["32 ГБ"],"Видеопроцессор...          rest   

  cat32_grouped                                          name1_bag  \
0          rest  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1          rest  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                           name2_bag  name1_len  name2_len  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          9         12   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          8          8   

                                           cat31_bag  cat31_len  cat32_len  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          3          3   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4          4   

                                           cat32_bag  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                          color1_bag  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                          color2_bag  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [55]:
feats = ["name1_bag", "name1_len", "name2_bag", "name2_len", "cat31_bag", "cat32_bag", "cat31_len", "cat32_len", "color1_bag", 'color2_bag']

In [56]:
X_test = feature_test[feats]

In [58]:
X_test

name1_bag  name1_len  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          9   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          8   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         14   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         12   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          7   
...                                                  ...        ...   
18079  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         33   
18080  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         11   
18081  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         18   
18082  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         14   
18083  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         12   

                                               name2_bag  name2_len  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         12   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          8   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          8   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         11   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          6   
...                                                  ...        ...   
18079  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         25   
18080  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         11   
18081  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         15   
18082  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         15   
18083  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...         12   

                                               cat31_bag  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                  ...   
18079  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18080  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18081  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18082  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18083  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               cat32_bag  cat31_len  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          3   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          3   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          3   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4   
...                                                  ...        ...   
18079  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          2   
18080  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4   
18081  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          1   
18082  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          1   
18083  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...          4   

       cat32_len                                         color1_bag  \
0              3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1              4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2              3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3              3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4              4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...          ...                                                ...   
18079          2  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18080          4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18081          1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
18082          1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [59]:
X_test_final = []

for i in range(len(X_test)):
    row = []
    row.extend(list(X_test[feats[0]].iloc[i]))
    row.extend(list(X_test[feats[2]].iloc[i]))
    row.extend(list(X_test[feats[4]].iloc[i]))
    row.extend(list(X_test[feats[5]].iloc[i]))
    row.extend(list(X_test[feats[8]].iloc[i]))
    row.extend(list(X_test[feats[9]].iloc[i]))
    row.extend([X_test[feats[b]].iloc[i] for b in [1,3,6,7]])
    X_test_final.append(row)

In [64]:
from catboost import CatBoostClassifier

model = CatBoostClassifier()

model.load_model("catboost_without_embs_1100v2_epochs.cbm")

In [65]:
predictions = model.predict_proba(X_test_final)

In [66]:
predictions

array([[0.91907967, 0.08092033],
       [0.8843131 , 0.1156869 ],
       [0.30515529, 0.69484471],
       ...,
       [0.9440747 , 0.0559253 ],
       [0.45548743, 0.54451257],
       [0.43247923, 0.56752077]])

In [67]:
predictions1 = model.predict(X_test_final)

In [68]:
predictions1

array([0., 0., 1., ..., 0., 1., 1.])

In [69]:
data_test["target"] = predictions[::, 1]

In [70]:
data_test

variantid1  variantid2    target
0        52076340   290590137  0.080920
1        64525522   204128919  0.115687
2        77243372   479860557  0.694845
3        86065820   540678372  0.131401
4        91566575   258840506  0.317032
...           ...         ...       ...
18079   666998614   667074522  0.002856
18080   670036240   670048449  0.293211
18081   670284509   684323809  0.055925
18082   692172005   704805270  0.544513
18083   704060220   704096517  0.567521

[18084 rows x 3 columns]

In [72]:
data_test.to_csv("sub_cat_666.csv", index = False)